# Digital Ocean App Platform Specification
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: tiktools
region: nyc

# Variables de entorno a nivel de app
envs:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
  - key: HOST
    value: "0.0.0.0"
  - key: DATABASE_URL
    value: "YOUR_DATABASE_URL_HERE"
    # Obtén de: Digital Ocean → Databases → Connection Details
  - key: JWT_SECRET
    value: "YOUR_JWT_SECRET_HERE"
    type: SECRET
    # Genera con: npm run generate:jwt

services:
  - name: web
    github:
      repo: Andres-back/TikTools
      branch: main
      deploy_on_push: true
    
    # Usar Dockerfile
    dockerfile_path: Dockerfile
    
    # Puerto interno
    http_port: 8080
    
    # Configuración de rutas para WebSocket
    routes:
      - path: /live
        preserve_path_prefix: true
      - path: /sync
        preserve_path_prefix: true
      - path: /
        preserve_path_prefix: true
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Recursos
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # Variables de entorno específicas del servicio
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: "production"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: HOST
        scope: RUN_TIME
        value: "0.0.0.0"

# Base de datos (opcional - si usas Digital Ocean Managed DB)
# databases:
#   - name: db-postgresql-nyc3-63457
#     engine: PG
#     version: "15"
